# Generated by Django 4.2.9 on 2024-04-09 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrreporting', '0006_alter_course_students'),
        ('users', '0004_remove_profile_student_profile_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='mrreporting.course'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics'),
        ),
    ]
