# Generated by Django 4.2.9 on 2024-02-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrreporting', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
