# Generated by Django 4.2.9 on 2024-02-03 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrreporting', '0004_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='course_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
