# Generated by Django 4.2.9 on 2024-04-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrreporting', '0008_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
